import type {
  CapabilityCondition,
  CapabilityDefinition,
  CapabilityDefinitionStep,
  InputContractField,
  OutputContract,
} from "./contracts.js";

const inputs: readonly InputContractField[] = [
  {
    name: "operator_username",
    type: "STRING",
    required: true,
    sensitivity: "NONE",
    description: "Operator identity used to enter the synthetic servicing portal.",
    format: "USERNAME",
    pattern: null,
    currency: null,
  },
  {
    name: "portal_password",
    type: "STRING",
    required: true,
    sensitivity: "CREDENTIAL",
    description: "Portal credential resolved only at invocation time.",
    format: "PASSWORD",
    pattern: null,
    currency: null,
  },
  {
    name: "member_id",
    type: "STRING",
    required: true,
    sensitivity: "PII",
    description: "Member identifier used for the deterministic member lookup.",
    format: "MEMBER_ID",
    pattern: "^M-[0-9]{5}$",
    currency: null,
  },
  {
    name: "product_name",
    type: "STRING",
    required: true,
    sensitivity: "NONE",
    description: "Savings product display name selected for preparation.",
    format: "PRODUCT_NAME",
    pattern: null,
    currency: null,
  },
  {
    name: "account_nickname",
    type: "STRING",
    required: true,
    sensitivity: "NONE",
    description: "Invocation-supplied nickname for the prepared subaccount.",
    format: "ACCOUNT_NICKNAME",
    pattern: null,
    currency: null,
  },
  {
    name: "initial_deposit",
    type: "USD_DECIMAL_STRING",
    required: true,
    sensitivity: "FINANCIAL",
    description: "Initial deposit represented as a two-decimal USD string.",
    format: "MONEY",
    pattern: "^(0|[1-9][0-9]*)[.][0-9]{2}$",
    currency: "USD",
  },
  {
    name: "funding_account",
    type: "STRING",
    required: true,
    sensitivity: "FINANCIAL",
    description: "Funding-account display reference selected at invocation time.",
    format: "ACCOUNT_DISPLAY_REFERENCE",
    pattern: null,
    currency: null,
  },
];

const outputs: OutputContract = {
  resultCategories: ["SUCCESS", "BUSINESS_OUTCOME", "FAILURE"],
  success: {
    category: "SUCCESS",
    status: {
      value: "READY_FOR_REVIEW",
      source: { kind: "PAGE_STATE", pageState: "ready-for-review" },
      sensitivity: "NONE",
    },
    accountCreated: {
      value: false,
      source: { kind: "CHECKPOINT_RESULT", checkId: "account-not-created" },
      sensitivity: "NONE",
    },
    reviewReceipt: {
      fields: [
        {
          name: "member",
          type: "STRING",
          sensitivity: "PII",
          source: { kind: "VALIDATED_INPUT", inputRef: "member_id" },
        },
        {
          name: "product",
          type: "STRING",
          sensitivity: "NONE",
          source: { kind: "VALIDATED_INPUT", inputRef: "product_name" },
        },
        {
          name: "nickname",
          type: "STRING",
          sensitivity: "NONE",
          source: { kind: "VALIDATED_INPUT", inputRef: "account_nickname" },
        },
        {
          name: "deposit",
          type: "USD_DECIMAL_STRING",
          sensitivity: "FINANCIAL",
          source: { kind: "VALIDATED_INPUT", inputRef: "initial_deposit" },
        },
        {
          name: "fundingAccount",
          type: "STRING",
          sensitivity: "FINANCIAL",
          source: { kind: "VALIDATED_INPUT", inputRef: "funding_account" },
        },
      ],
    },
  },
  businessOutcome: { category: "BUSINESS_OUTCOME", codeType: "ENUM" },
  failure: { category: "FAILURE", codeType: "ENUM" },
};

const retryInput = {
  maxAttempts: 2,
  backoffMs: 250,
  retryOn: ["STALE_TARGET", "TRANSIENT_TIMEOUT"],
  idempotentOnly: true,
} as const;

const retryClick = {
  maxAttempts: 1,
  backoffMs: 0,
  retryOn: [],
  idempotentOnly: true,
} as const;

const steps: readonly CapabilityDefinitionStep[] = [
  {
    purpose: "ENTER_OPERATOR_USERNAME",
    sourceActionType: "fill_element_from_input",
    operation: "FILL",
    target: {
      role: "textbox",
      accessibleName: "Operator username",
      label: "Operator username",
      trustedControlId: null,
    },
    inputRef: "operator_username",
    startingPageState: "operator-login",
    resultingPageState: "operator-login",
    timeoutMs: 10_000,
    retry: retryInput,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SAFE",
  },
  {
    purpose: "ENTER_PORTAL_PASSWORD",
    sourceActionType: "fill_element_from_input",
    operation: "FILL",
    target: {
      role: "textbox",
      accessibleName: "Password",
      label: "Password",
      trustedControlId: null,
    },
    inputRef: "portal_password",
    startingPageState: "operator-login",
    resultingPageState: "operator-login",
    timeoutMs: 10_000,
    retry: retryInput,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SENSITIVE",
  },
  {
    purpose: "SUBMIT_OPERATOR_LOGIN",
    sourceActionType: "click_element",
    operation: "CLICK",
    target: {
      role: "button",
      accessibleName: "Log in",
      label: null,
      trustedControlId: null,
    },
    inputRef: null,
    startingPageState: "operator-login",
    resultingPageState: "employee-dashboard",
    timeoutMs: 15_000,
    retry: retryClick,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SAFE",
  },
  {
    purpose: "OPEN_MEMBER_SEARCH",
    sourceActionType: "click_element",
    operation: "CLICK",
    target: {
      role: "link",
      accessibleName: "Member Search\nLocate a member and view account services.",
      label: null,
      trustedControlId: null,
    },
    inputRef: null,
    startingPageState: "employee-dashboard",
    resultingPageState: "member-search",
    timeoutMs: 15_000,
    retry: retryClick,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SAFE",
  },
  {
    purpose: "ENTER_MEMBER_ID",
    sourceActionType: "fill_element_from_input",
    operation: "FILL",
    target: {
      role: "textbox",
      accessibleName: "Member ID",
      label: "Member ID",
      trustedControlId: null,
    },
    inputRef: "member_id",
    startingPageState: "member-search",
    resultingPageState: "member-search",
    timeoutMs: 10_000,
    retry: retryInput,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SENSITIVE",
  },
  {
    purpose: "SUBMIT_MEMBER_SEARCH",
    sourceActionType: "click_element",
    operation: "CLICK",
    target: {
      role: "button",
      accessibleName: "Search",
      label: null,
      trustedControlId: null,
    },
    inputRef: null,
    startingPageState: "member-search",
    resultingPageState: "member-profile",
    timeoutMs: 15_000,
    retry: retryClick,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SAFE",
  },
  {
    purpose: "OPEN_SAVINGS_APPLICATION",
    sourceActionType: "click_element",
    operation: "CLICK",
    target: {
      role: "link",
      accessibleName: "Add savings subaccount",
      label: null,
      trustedControlId: null,
    },
    inputRef: null,
    startingPageState: "member-profile",
    resultingPageState: "savings-application",
    timeoutMs: 15_000,
    retry: retryClick,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SAFE",
  },
  {
    purpose: "SELECT_SAVINGS_PRODUCT",
    sourceActionType: "select_option_from_input",
    operation: "SELECT_OPTION",
    target: {
      role: "combobox",
      accessibleName: "Product",
      label: "Product",
      trustedControlId: null,
    },
    inputRef: "product_name",
    startingPageState: "savings-application",
    resultingPageState: "savings-application",
    timeoutMs: 10_000,
    retry: retryInput,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SAFE",
  },
  {
    purpose: "ENTER_ACCOUNT_NICKNAME",
    sourceActionType: "fill_element_from_input",
    operation: "FILL",
    target: {
      role: "textbox",
      accessibleName: "Account nickname",
      label: "Account nickname",
      trustedControlId: null,
    },
    inputRef: "account_nickname",
    startingPageState: "savings-application",
    resultingPageState: "savings-application",
    timeoutMs: 10_000,
    retry: retryInput,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SAFE",
  },
  {
    purpose: "ENTER_INITIAL_DEPOSIT",
    sourceActionType: "fill_element_from_input",
    operation: "FILL",
    target: {
      role: "textbox",
      accessibleName: "Initial deposit",
      label: "Initial deposit",
      trustedControlId: null,
    },
    inputRef: "initial_deposit",
    startingPageState: "savings-application",
    resultingPageState: "savings-application",
    timeoutMs: 10_000,
    retry: retryInput,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SENSITIVE",
  },
  {
    purpose: "SELECT_FUNDING_ACCOUNT",
    sourceActionType: "select_option_from_input",
    operation: "SELECT_OPTION",
    target: {
      role: "combobox",
      accessibleName: "Funding account",
      label: "Funding account",
      trustedControlId: null,
    },
    inputRef: "funding_account",
    startingPageState: "savings-application",
    resultingPageState: "savings-application",
    timeoutMs: 10_000,
    retry: retryInput,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SENSITIVE",
  },
  {
    purpose: "CONTINUE_TO_REVIEW",
    sourceActionType: "click_element",
    operation: "CLICK",
    target: {
      role: "button",
      accessibleName: "Continue to review",
      label: null,
      trustedControlId: null,
    },
    inputRef: null,
    startingPageState: "savings-application",
    resultingPageState: "ready-for-review",
    timeoutMs: 15_000,
    retry: retryClick,
    expectedOwnership: "AUTOMATION",
    expectedRisk: "SAFE",
  },
];

const checkpointConditions: readonly CapabilityCondition[] = [
  { id: "page-state-ready-for-review", kind: "PAGE_STATE_EQUALS", pageState: "ready-for-review" },
  {
    id: "review-heading",
    kind: "HEADING_EQUALS",
    heading: "Review Savings Subaccount",
  },
  {
    id: "review-member",
    kind: "REVIEW_FIELD_MATCHES_INPUT",
    field: "Member",
    inputRef: "member_id",
  },
  {
    id: "review-product",
    kind: "REVIEW_FIELD_MATCHES_INPUT",
    field: "Product",
    inputRef: "product_name",
  },
  {
    id: "review-nickname",
    kind: "REVIEW_FIELD_MATCHES_INPUT",
    field: "Nickname",
    inputRef: "account_nickname",
  },
  {
    id: "review-deposit",
    kind: "REVIEW_FIELD_MATCHES_INPUT",
    field: "Initial deposit",
    inputRef: "initial_deposit",
  },
  {
    id: "review-funding-account",
    kind: "REVIEW_FIELD_MATCHES_INPUT",
    field: "Funding account",
    inputRef: "funding_account",
  },
  {
    id: "account-not-created",
    kind: "TEXT_CONTAINS",
    text: "No account has been created.",
  },
  {
    id: "open-account-policy",
    kind: "CONTROL_PRESENT",
    target: {
      requiredPageState: "ready-for-review",
      controlKind: "BUTTON",
      strategies: [
        {
          kind: "EXACT_ROLE_AND_ACCESSIBLE_NAME",
          pageState: "ready-for-review",
          role: "button",
          accessibleName: "Open Account",
          exact: true,
          expectedMatches: 1,
        },
      ],
      expectedOwnership: "NONE",
      expectedRisk: "IRREVERSIBLE",
      ambiguityPolicy: "FAIL_CLOSED",
      robustness: {
        tier: "HIGH",
        signalCodes: ["PAGE_STATE", "SEMANTIC_ROLE", "ACCESSIBLE_NAME"],
        rationaleCode: "CURATED_EXACT_SEMANTIC_IDENTITY",
      },
    },
  },
  {
    id: "open-account-not-executed",
    kind: "NO_EXECUTED_TARGET",
    role: "button",
    accessibleName: "Open Account",
  },
  {
    id: "forbidden-owner-not-executed",
    kind: "NO_EXECUTED_OWNERS",
    owners: ["HUMAN", "NONE"],
  },
];

export const PREPARE_SAVINGS_SUBACCOUNT_DEFINITION: CapabilityDefinition = {
  definitionVersion: "1.0.0",
  capability: {
    id: "prepare_savings_subaccount",
    title: "Prepare Savings Subaccount",
    description:
      "Prepare a savings subaccount and stop after deterministic verification of the final review screen.",
    version: "1.0.0",
  },
  inputs,
  outputs,
  surface: {
    kind: "LEGACY_WEB",
    entryPoint: { path: "/login", expectedInitialPageState: "operator-login" },
  },
  preconditions: [
    { id: "initial-page-state", kind: "PAGE_STATE_EQUALS", pageState: "operator-login" },
  ],
  steps,
  executionPolicy: {
    maxTotalRuntimeMs: 180_000,
    defaultStepTimeoutMs: 10_000,
    maxStepAttempts: 2,
  },
  checkpoint: {
    id: "ready-for-review",
    mode: "ALL",
    conditions: checkpointConditions,
    successStatus: "READY_FOR_REVIEW",
  },
  postconditions: checkpointConditions,
  outcomes: {
    businessOutcomes: [
      {
        code: "MEMBER_NOT_FOUND",
        category: "BUSINESS_OUTCOME",
        terminal: true,
        detector: {
          mode: "ALL",
          conditions: [
            { kind: "PAGE_STATE_EQUALS", pageState: "member-search" },
            {
              kind: "TEXT_TEMPLATE_PRESENT",
              template: "No member was found for ID {member_id}.",
              bindings: { member_id: "member_id" },
            },
          ],
        },
      },
    ],
    recoverableConditions: [
      { code: "STALE_TARGET", maxOccurrences: 1, terminal: false },
      { code: "TRANSIENT_TIMEOUT", maxOccurrences: 1, terminal: false },
    ],
    failureCodes: [
      "UNEXPECTED_PAGE_STATE",
      "TARGET_AMBIGUOUS",
      "POLICY_VIOLATION",
      "TIMEOUT",
      "SESSION_LOSS",
      "CHECKPOINT_FAILED",
    ],
  },
  safetyPolicy: {
    allowedOwners: ["AUTOMATION"],
    forbiddenOwners: ["HUMAN", "NONE"],
    allowedRisks: ["SAFE", "SENSITIVE"],
    forbiddenRisks: ["IRREVERSIBLE"],
    forbiddenTargets: [{ role: "button", accessibleName: "Open Account", exact: true }],
    externalNavigation: "FORBIDDEN",
    ambiguity: "FAIL_CLOSED",
  },
  compatibility: {
    applicationFamily: "heritage-community-credit-union-member-portal",
    tenantScope: ["synthetic-training"],
    applicationVariants: ["server-rendered-legacy-v1"],
    semanticSurfaceContract: "1.0.0",
    adapterKinds: ["LEGACY_WEB", "DESKTOP_ACCESSIBILITY"],
  },
};
